
services:
  web:
    build: .
    image: secdev-seed:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=secdev-seed
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5
    read_only: true
    volumes:
      - appdb:/app/app.db
    cap_drop: [ "ALL" ]
    security_opt:
      - no-new-privileges:true
volumes:
  appdb: